"""Real-time sign-language digit detection from a webcam.

Loads the trained SVM (+ scaler) and runs live: MediaPipe extracts 21 hand
landmarks per frame (42 features), the scaler normalizes them, and the SVM
predicts the digit, which is drawn over the detected hand. Press 'q' to quit.

Prerequisites — train the model first so the artifacts exist:
    run svmfin.ipynb   (creates model.p and scaler.pickle)

Then:
    python realtime_predict.py

The model files are gitignored (regenerated by the notebook), so if they are
missing this script prints a clear message instead of crashing.
"""
from __future__ import annotations

import argparse
import os
import pickle
import sys

import cv2
import mediapipe as mp
import numpy as np

mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles


def _load(path, what):
    if not os.path.exists(path):
        sys.exit(
            f"Missing {what}: '{path}'. Train the model first by running "
            f"svmfin.ipynb (it creates model.p and scaler.pickle)."
        )
    with open(path, "rb") as f:
        return pickle.load(f)


def run(model_path="model.p", scaler_path="scaler.pickle",
        label_encoder_path="label_encoder.pickle", camera=0):
    model = _load(model_path, "model")["model"]
    scaler = _load(scaler_path, "scaler")

    # The SVM notebook trains on raw digit labels, so model.predict already
    # returns the digit. Use a label encoder only if one was actually saved.
    label_encoder = None
    if os.path.exists(label_encoder_path):
        with open(label_encoder_path, "rb") as f:
            label_encoder = pickle.load(f)

    def to_text(pred):
        if label_encoder is not None:
            try:
                return str(label_encoder.inverse_transform([int(pred)])[0])
            except (ValueError, TypeError):
                pass
        return str(pred)

    hands = mp_hands.Hands(static_image_mode=False, min_detection_confidence=0.3)
    cap = cv2.VideoCapture(camera)
    if not cap.isOpened():
        sys.exit(f"Could not open camera index {camera}.")

    print("Running — press 'q' in the video window to quit.")
    while True:
        ok, frame = cap.read()
        if not ok:
            print("Failed to capture frame; exiting.")
            break

        H, W, _ = frame.shape
        results = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    frame, hand_landmarks, mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style(),
                )
                xs = [lm.x for lm in hand_landmarks.landmark]
                ys = [lm.y for lm in hand_landmarks.landmark]
                features = []
                for x, y in zip(xs, ys):
                    features += [x, y]

                if len(features) == 42:  # one hand, 21 landmarks x (x, y)
                    scaled = scaler.transform([np.asarray(features)])
                    pred = model.predict(scaled)[0]
                    text = to_text(pred)
                    x1, y1 = int(min(xs) * W) - 10, int(min(ys) * H) - 10
                    x2, y2 = int(max(xs) * W) - 10, int(max(ys) * H) - 10
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 0), 4)
                    cv2.putText(frame, text, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX,
                                1.3, (0, 0, 0), 3, cv2.LINE_AA)

        cv2.imshow("Sign Language Digit Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model", default="model.p")
    p.add_argument("--scaler", default="scaler.pickle")
    p.add_argument("--label-encoder", default="label_encoder.pickle")
    p.add_argument("--camera", type=int, default=0)
    args = p.parse_args()
    run(args.model, args.scaler, args.label_encoder, args.camera)
